name: OWASP ZAP Full Scan

on:
  push:
    branches:
      - main

jobs:
  dast_scan:
    runs-on: ubuntu-latest
    steps:
      # Checkout do código do repositório
      - name: Checkout code
        uses: actions/checkout@v3

      # Executa o OWASP ZAP Full Scan
      - name: Run OWASP ZAP Full Scan
        uses: zaproxy/action-full-scan@v0.12.0
        with:
          target: "http://www.testeapi.com"
          rules_file: ".zap/rules-config.json" # Opcional: Arquivo de configuração de regras
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Verifica resultado
      - name: Check scan results
        run: |
          if grep -q "Broken Authentication" zap.out; then
            echo "⚠️ Vulnerabilidades de Broken Authentication detectadas!";
            exit 1;
          else
            echo "✅ Nenhuma vulnerabilidade de Broken Authentication encontrada.";
          fi
