name: DAST-OWASP-ZAP
on:
  push:
    branches:
      - main
jobs:
  dast_scan:
    runs-on: ubuntu-latest
    steps:
      # Verifica código-fonte
      - name: Checkout code
        uses: actions/checkout@v3

      # Configura OWASP ZAP
      - name: Start OWASP ZAP
        run: |
          docker run -d --name owasp-zap -p 8080:8080 owasp/zap2docker-stable:latest zap.sh -daemon -host 0.0.0.0 -port 8080
          sleep 30 # Aguarda OWASP ZAP iniciar

      # Executa varredura DAST
      - name: Run OWASP ZAP Scan
        run: |
          docker exec owasp-zap zap-cli open-url http://www.testeapi.com
          docker exec owasp-zap zap-cli quick-scan --scanners xss,sqli,auth -o http://www.testeapi.com

      # Valida resultados
      - name: Check for Broken Authentication vulnerabilities
        run: |
          if docker exec owasp-zap zap-cli alerts -l High | grep -q "Broken Authentication"; then
            echo "⚠️ Vulnerabilidades de Broken Authentication detectadas!";
            exit 1;
          else
            echo "✅ Nenhuma vulnerabilidade de Broken Authentication encontrada.";
          fi

      # Finaliza o OWASP ZAP
      - name: Stop OWASP ZAP
        run: docker stop owasp-zap && docker rm owasp-zap
